# Conclusion

The first part is to investigate whether vaccination has an impact on the spread of COVID-19. By analyzing the five states with the largest number of vaccinations, we found that the vaccination rate is inversely related to the spread of the epidemic. This relationship has also been confirmed by national data. From this we can get that vaccination can curb the spread of the epidemic.

The second part is to analyze the relationship between hospital-related data and mortality. According to analysis, we did not find a clear relationship between hospital capacity and mortality. This may be due to other factors affecting the relationship between these two. So, in order to further analyze, we will collect more hospital-related data, similar to data such as number of ventilators or the number of doctors. Under the control of other variables, we will do further analysis. Regarding the relationship between hospitalization rate and death rate, we found that hospitalization rate and death rate are positively correlated. One possible explanation is that people may only be hospitalized for treatment when they become severely ill. And because there is no specific medicine, it is difficult for severely ill patients to be cured, which leads to a positive correlation. 

The third part is to argue if covid will affect life expectancy. Life expectancy at birth, that is, the average life expectancy of newborns, is a general indicator to measure population mortality and health status. The analysis is as follows: First, age is a factor that causes so many COVID-19 deaths and diagnoses. From the data in the table, it can be known that the more severe the aging of the country or region, the greater the number of COVID-19 deaths. We have reason to believe that the elderly is more susceptible to the coronavirus and have a higher mortality rate. Second, each person's own underlying diseases and some complications are another important factor in the death rate of the COVID-19. People with these diseases are more susceptible to the virus than normal healthy people because they have problems with their own immune system. This problem is more likely to occur in the elderly. Elderly people with autoimmune system diseases and complications should take precautions and follow the doctor's instructions to take medicine to avoid contracting COVID-19.
From the above two important factors, we can see that for the elderly (the main target audience of the new coronavirus), what they must do is to protect themselves and seek medical treatment in time. Special services for the elderly should also be done in senior care institutions. The state finance should also provide appropriate subsidies and appropriations for these institutions to ensure that the elderly can also spend the rest of their lives healthily.

In this project, we encountered lots of problems and learned a lot in the process of solving these issues. 

After we got the raw data, missing value was the first problem that we need to deal with. There were lots of techniques to choose to solve missing values, like forward filling, backward filling, fill by means, delete... For different types of features, we used different methods by doing lots of research online. When we were doing data cleaning and transformation, we found that some of the data was wrong when being collected. We had to find means to correct these values. 

When it came to the graphs, things were more complicated. We learned a lot of visualization techniques in this semester's class and we needed to find the proper graphs to tell our data story. All graphs had to be well-designed and could help to explain the main idea. In the future, we can improve our graphs by using better methods, like putting bar plots side by side. D3 is a powerful technique. We only used a little in this project. It doesn't require a server to run like shiny app. We can design more interactive graphs that can explain our ideas to our readers better.



